version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pgsql"
      POSTGRES_DB: "quarkus"
    ports:
      - "15432:5432"
    volumes:
      - ./test-data:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "kennet.emerson@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "pgsql"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-compose-network
      
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "5778:5775"
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge
